#define BAKU_EXIT_SUCCESS 0
#define BAKU_EXIT_ARGUMENT_ERROR -1
#define BAKU_EXIT_DB_ERROR -2
#define BAKU_EXIT_PATH_ERROR -3


std::string SQL_CREATE_TABLE = "CREATE TABLE IF NOT EXISTS files ( _idef TEXT PRIMARY KEY, _hash TEXT )";